### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by annejan** [SHA2017-badge/Hatchery#15]
How do we want to categorise apps?

* SHA2017
* Games
* Libraries
* Tools
* Hacking
* ???

**Comment by Kartoffel** [comment]
* Graphics
* Hardware
* Utility
* Wearable
* Data
* Silly
* Uncategorised

Some more, judge for yourself which of those may be relevant.

**Comment by sebastius** [comment]
* Unusable
* Troll
* Virus

**Comment by sebastius** [comment]
Adult
Event-augmenting

**Comment by annejan** [comment]
```
            'Uncategorised',
            'Event related',
            'Games',
            'Graphics',
            'Hardware',
            'Utility',
            'Wearable',
            'Data',
            'Silly',
            'Hacking',
            'Troll',
            'Unusable',
            'Adult',
            'Virus'
```

**Comment by annejan** [comment]
Forgot to actually add a drop-down and JSON views for them . .
