### ISSUE TITLE
Permissions and some thoughts about Security

### ISSUE THREAD

**Issue by doebi** [SHA2017-badge/Hatchery#7]
Recently i signed up on the hatchery to just have a look at it.

I was pretty surprised, that even with a throwaway email address and random password one can get full access to every egg up there.
It is pretty easy to insert malicious code to any of the already present eggs.

I would suggest an egg is bond to a unique account and can only be edited by that account.

PS.: i added a 'malicious' line at the mandelbrot egg

**Comment by annejan** [comment]
Indeed there is currently no ACL
I'm thinking eggs should indeed be lockable by the creator . .
Possibly with the option to select maintainers.

**Comment by Kartoffel** [comment]
IMO eggs should, by default, only be editable by their creator. Perhaps with the option to allow others to edit it.

**Comment by annejan** [comment]
Currently being worked on, please use PR for comments https://github.com/SHA2017-badge/Hatchery/pull/20
